<?php
/** @var \Magento\Framework\View\TemplateEngineInterface $this */
/** @var \Cwax\Banner\Block\Widget\Banner $block */
/** @var \Magento\Csp\Api\InlineUtilInterface $csp */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php //= $escaper->escapeHtml($block->getData('banner_div')) ?>
<?= $block->getData('banner_div') ?>
